version: '3'

services:
  plex:
    image: plexinc/pms-docker
    hostname: PlexServer
    restart: always
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      PLEX_CLAIM: "${PLEX_CLAIM}"
      TZ: "${TZ}"
      ADVERTISE_IP: "${ADVERTISE_IP}"
      ALLOWED_NETWORKS: "${ALLOWED_NETWORKS}"
    volumes:
      - ./data:/data
      - ./transcode:/transcode
      - ./config:/config
